fix smooth quant for llama
without this it errors out with:

Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 456, in <module>
    main()
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 448, in main
    convert_and_save_hf(args)
  File "/app/tensorrt_llm/examples/llama/convert_checkpoint.py", line 353, in convert_and_save_hf
    LLaMAForCausalLM.quantize(args.model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 405, in quantize
    convert.quantize(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1395, in quantize
    weights = load_weights_from_hf(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1437, in load_weights_from_hf
    weights = convert_hf_llama(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1089, in convert_hf_llama
    convert_layer(l)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 725, in convert_layer
    get_tllm_linear_sq_weight(int8_weights,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 610, in get_tllm_linear_sq_weight
    results[prefix + 'per_channel_scale'] = torch.Tensor([
ValueError: only one element tensors can be converted to Python scalars

we can also check the shapes:
cur_per_channel_value.shape -> torch.Size([6144])
col_shape -> [1, 6144]

so it's clear that we meant to convert the tensor without []