[TRTLLM-9209][infra] Upgrade precommit-hooks to v6.0.0
The version we are currently using has a bug when the source directory
is a worktree. Among the list of files provided to hooks as "modified"
is the COMMIT_EDITMSG file, which causes the "check-added-large-files"
hook to always fail. The failure trace in this case is:

```
Traceback (most recent call last):
  File "/home/redacted/.cache/pre-commit/reporscg788n/py_env-python3.12/bin/check-added-large-files", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/redacted/.cache/pre-commit/reporscg788n/py_env-python3.12/lib/python3.12/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/.cache/pre-commit/reporscg788n/py_env-python3.12/lib/python3.12/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/redacted/.cache/pre-commit/reporscg788n/py_env-python3.12/lib/python3.12/site-packages/pre_commit_hooks/check_added_large_files.py", line 18, in filter_lfs_files
    check_attr = subprocess.run(
                 ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('git', 'check-attr', 'filter', '-z', '--stdin')' returned non-zero exit status 128.
```

This commit upgrades pre-commit-hooks to v6.0.0, which fixes this issue.

Signed-off-by: Josh Bialkowski <1309820+cheshirekow@users.noreply.github.com>