Update fused_moe_triton.py to cooperate with the change in OAI Triton 3.6.0
Fix the following issue:

fused_moe_triton.py:177, in __call__
    expt_scal, expt_indx, bitmatrix = topk(logits, ...)
TypeError: cannot unpack non-iterable SparseMatrix object

Signed-off-by: Yanchao Lu <yanchaol@nvidia.com>